services:
  nginx:
    image: nginx:latest
    container_name: nginx

    
    volumes:
    - ./nginx/nginxdev.conf:/etc/nginx/nginx.conf
    - ./miniApp/dist:/usr/share/nginx/html
    - ./UgostyMainService/media:/app/UgostyMainService/media  


    ports:
      - "80:80"

    depends_on:
        - miniapp
 

    networks:
      - webnet
   

  miniapp:
    build: 
      context: ./miniApp
    
    container_name: miniappcontainer
    volumes:
      - ./miniApp/dist:/app/dist

    ports:
      - "3000:80"



  backend-main:
    container_name: backend
    command: gunicorn UgostyMainService.wsgi:application --bind 0.0.0.0:8000

    build:
      context: ./UgostyMainService
      dockerfile: Dockerfile

    volumes:
      - ./UgostyMainService/:/usr/src/UgostyMainService/
      - ./UgostyMainService/media/:/app/UgostyMainService/media/

    ports:
      - "8000:8000"

    networks:
      - webnet
      - dbugostynet



  yadrobot:
    build: ./botYadro
    container_name: yadrobot
    ports:
      - "4000:4000"

    networks:
      - webnet
      - dbugostynet



  pgadmin:

    container_name: pgadmin4_container
    image: 'docker.io/dpage/pgadmin4:latest'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root

      
    
    ports:
      - "5050:80"


    networks:
      - webnet
      - dbugostynet


networks:
  webnet:
    driver: bridge

  dbugostynet:
    external: true