# HTTP сервер для проверки и редиректа на HTTPS
server {
    listen 80;
    server_name ugosty.ru www.ugosty.ru;

    # Путь для Certbot challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Редирект с HTTP на HTTPS
    location / {
        return 301 https://$host$request_uri;
    }

    location /api/ {
        rewrite ^/api(/.*)$ $1 break;  # Убираем префикс "/api"
        proxy_pass http://backend:8000;  # Прокси на backend
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    



}

# HTTPS сервер с настройками SSL
server {
    listen 443 ssl http2;
    server_name ugosty.ru www.ugosty.ru;

    # Пути к SSL сертификатам
    ssl_certificate /etc/letsencrypt/live/ugosty.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ugosty.ru/privkey.pem;

    # Дополнительные SSL-настройки для безопасности
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256';
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Заголовки безопасности
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;

    # Обработка ошибок
    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
