events { 
    worker_connections  4096;  
} 

http { 
    include       mime.types;  # Добавлено для определения MIME-типов
    default_type  application/octet-stream;

    server { 
        listen 80; 
        server_name localhost; 

        location / { 
            root /usr/share/nginx/html; 
            index index.html index.htm; 

            try_files $uri $uri/ /index.html; # Для поддержки маршрутизации в React Router 
        } 

        error_page 404 /index.html; # Обработка 404 ошибок 
    }
}
