# Generated by Django 5.0.7 on 2025-01-01 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('img_buns', models.ImageField(upload_to='buns')),
                ('price', models.IntegerField(default=0)),
                ('created_at', models.CharField(max_length=50)),
                ('color_treats', models.TextField(max_length=120)),
            ],
            options={
                'db_table': 'Buns',
            },
        ),
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_telegram', models.CharField(max_length=120, unique=True)),
                ('chat_id', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='DonationBunQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('bun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.buns')),
            ],
            options={
                'db_table': 'donation_buns',
            },
        ),
        migrations.CreateModel(
            name='DonationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='buns/')),
                ('status_banned', models.BooleanField(default=False)),
                ('buns', models.ManyToManyField(related_name='donation_profiles', through='accounts.DonationBunQuantity', to='accounts.buns')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'donation_profiles',
            },
        ),
        migrations.AddField(
            model_name='donationbunquantity',
            name='donation_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.donationprofile'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=50)),
                ('social_media', models.CharField(max_length=50)),
                ('donation_message', models.TextField()),
                ('data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_amount', models.IntegerField(blank=True, default=0)),
                ('type_payout', models.BooleanField(default=False, null=True)),
                ('donation_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.donationprofile')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.AlterUniqueTogether(
            name='donationbunquantity',
            unique_together={('donation_profile', 'bun')},
        ),
    ]
