# Generated by Django 5.0.7 on 2025-01-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='chat_id',
            field=models.IntegerField(max_length=120),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='id_telegram',
            field=models.IntegerField(max_length=120, unique=True),
        ),
    ]
