# Generated by Django 5.0.7 on 2025-01-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_telegramprofile_chat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramPostsWithBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('text', models.TextField()),
                ('button_text', models.TextField(blank=True)),
                ('button_link', models.TextField(blank=True)),
            ],
        ),
    ]
