# Generated by Django 5.0.7 on 2025-01-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_telegrampostswithbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrampostswithbot',
            name='thumbnail',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
