# Generated by Django 5.0.7 on 2025-01-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_telegrampostswithbot_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrampostswithbot',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
