# Generated by Django 5.0.7 on 2025-01-10 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_telegrampostswithbot_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationprofile',
            name='telegram_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.telegramprofile'),
        ),
    ]
