# Generated by Django 5.0.7 on 2025-01-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_donationprofile_telegram_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='chat_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='id_telegram',
            field=models.IntegerField(unique=True),
        ),
    ]
