# Generated by Django 5.0.7 on 2025-01-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_telegramprofile_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='id_telegram',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
