# Generated by Django 5.0.7 on 2025-01-10 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_telegramprofile_id_telegram'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='telegramprofile',
            table='telegram_profiles',
        ),
    ]
